project_id = "rykbyzediigwcstuzvnf"

[functions.send-message-email]
verify_jwt = false

[functions.send-system-email]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.assign-scholar-to-project]
verify_jwt = false

[functions.cleanup-orphan-users]
verify_jwt = false

[functions.create-users-batch]
verify_jwt = false

[functions.delete-users]
verify_jwt = false

[functions.manage-users]
verify_jwt = false

[functions.monthly-report-reminder]
verify_jwt = false