project_id = "rykbyzediigwcstuzvnf"

[functions.send-message-email]
verify_jwt = false

[functions.send-system-email]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.assign-scholar-to-project]
verify_jwt = false

[functions.cleanup-orphan-users]
verify_jwt = false

[functions.create-users-batch]
verify_jwt = false

[functions.delete-users]
verify_jwt = false

[functions.manage-users]
verify_jwt = false

[functions.monthly-report-reminder]
verify_jwt = false

[functions.admin-list-members]
verify_jwt = false

[functions.send-org-invite-email]
verify_jwt = false

[functions.generate-scholarship-pdf]
verify_jwt = false

[functions.generate-thematic-project-pdf]
verify_jwt = false

[functions.generate-executive-report-pdf]
verify_jwt = false

[functions.generate-monthly-report-pdf]
verify_jwt = false